import type { LogoRef } from "./slides";

const L = import.meta.env.BASE_URL + "presentations/media/logos/";

/** Shared "Trusted By" logo wall — real TAQA Arabia clients & partners,
    extracted from the source decks. Reused identically across every
    Client Presentations deck (the source decks all show the same wall). */
export const TRUSTED_BY_LOGOS: LogoRef[] = [
  { src: L + "logo-tui.png", alt: "TUI" },
  { src: L + "logo-elsewedy-cement.png", alt: "El Sewedy Cement" },
  { src: L + "logo-imkan.png", alt: "Imkan" },
  { src: L + "logo-lmd.png", alt: "LMD" },
  { src: L + "logo-rock-ceramic.png", alt: "Rock Ceramic" },
  { src: L + "logo-al-burouj.png", alt: "Al Burouj" },
  { src: L + "logo-oic-ein-sokhna.png", alt: "OIC Ein Sokhna" },
  { src: L + "logo-somabay.png", alt: "Soma Bay" },
  { src: L + "logo-silversands.png", alt: "Silversands" },
  { src: L + "logo-al-futtaim-group.png", alt: "Al-Futtaim Group" },
  { src: L + "logo-ajwa-group.png", alt: "Ajwa Group" },
  { src: L + "logo-rondy-ceramic.png", alt: "Rondy Ceramic" },
  { src: L + "logo-idg.png", alt: "Industrial Development Group" },
  { src: L + "logo-rixos-hotels.png", alt: "Rixos Hotels" },
  { src: L + "logo-alico-egypt.png", alt: "Alico Egypt" },
  { src: L + "logo-ebic.png", alt: "EBIC" },
  { src: L + "logo-lavista.png", alt: "La Vista Developments" },
  { src: L + "logo-city-edge-developments.png", alt: "City Edge Developments" },
  { src: L + "logo-travco-group.png", alt: "Travco Group" },
  { src: L + "logo-lafarge-holcim.png", alt: "Lafarge — A Member of Holcim" },
  { src: L + "logo-maven.png", alt: "Maven Developments" },
  { src: L + "logo-hyde-park.png", alt: "Hyde Park Developments" },
  { src: L + "logo-arabian-cement.png", alt: "Arabian Cement" },
  { src: L + "logo-almarasem.png", alt: "Almarasem Development" },
  { src: L + "logo-opc.png", alt: "OPC" },
  { src: L + "logo-angel.png", alt: "Angel" },
  { src: L + "logo-scfp.png", alt: "SCFP" },
  { src: L + "logo-ezzsteel.png", alt: "Ezz Steel" },
  { src: L + "logo-sumed.png", alt: "Sumed" },
  { src: L + "logo-palm-hills.png", alt: "Palm Hills Developments" },
  { src: L + "logo-pickalbatros.png", alt: "Pickalbatros Hotels & Resorts" },
  { src: L + "logo-tatweer-misr.png", alt: "Tatweer Misr" },
  { src: L + "logo-cairo-festival-city.png", alt: "Cairo Festival City" },
  { src: L + "logo-steigenberger.png", alt: "Steigenberger Hotels & Resorts" },
  { src: L + "logo-scimitar.png", alt: "Scimitar Production Egypt" },
  { src: L + "logo-albatros.png", alt: "Albatros" },
  { src: L + "logo-address-hotels.png", alt: "Address Hotels + Resorts" },
  { src: L + "logo-cleopatra.png", alt: "Cleopatra Luxury Resort" },
  { src: L + "logo-orascom-development.png", alt: "Orascom Development" },
  { src: L + "logo-elsewedy-industrial-dev.png", alt: "Elsewedy Industrial Development" },
  { src: L + "logo-makadi-heights.png", alt: "Makadi Heights" },
  { src: L + "logo-emaar.png", alt: "Emaar" },
  { src: L + "logo-midea.png", alt: "Midea" },
  { src: L + "logo-marassi.png", alt: "Marassi North Coast" },
  { src: L + "logo-citystars.png", alt: "City Stars" },
  { src: L + "logo-kpi.png", alt: "KPI" },
  { src: L + "logo-egpc.png", alt: "EGPC" },
  { src: L + "logo-marakez.png", alt: "Marakez" },
  { src: L + "logo-saint-gobain.png", alt: "Saint-Gobain" },
  { src: L + "logo-hikma.png", alt: "Hikma" },
  { src: L + "logo-polaris-zamil.png", alt: "Polaris Zamil" },
  { src: L + "logo-knauf.png", alt: "Knauf" },
  { src: L + "logo-misr-beni-suwayf-cement.png", alt: "Misr Beni-Suwayf Cement" },
  { src: L + "logo-efc.png", alt: "EFC" },
  { src: L + "logo-mountain-view.png", alt: "Mountain View" },
  { src: L + "logo-polaris-parks.png", alt: "Polaris Parks" },
  { src: L + "logo-qatari-diar.png", alt: "Qatari Diar" },
  { src: L + "logo-sodic.png", alt: "SODIC" },
  { src: L + "logo-danone.png", alt: "Danone" },
  { src: L + "logo-global-pharma.png", alt: "Global Pharma" },
];
